"""Self-contained graphify pipeline for CI and for headless local runs.

Builds a knowledge graph over this repository and writes
graphify-out/{graph.json,GRAPH_REPORT.md}.

- Code is extracted structurally (AST, deterministic, no LLM, no API key).
  SmartWard is ~120 Swift files, so the graph's backbone is free and stable.
- Docs get semantic extraction via Gemini when GEMINI_API_KEY is set;
  otherwise the semantic pass is skipped and the graph is code-only. That is
  why this script is safe to run in CI with no secrets configured.
- Community labels are deterministic: each community is named after its
  highest-degree member, so re-running on an unchanged tree reproduces the
  same report.

Everything runs inside main() because AST extraction uses a process pool and
macOS defaults to the spawn start method, which re-imports this module in
every worker. Module-level work would run there too and break the pool.

Run it with:  python scripts/graphify_pipeline.py
"""
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(os.environ.get("GRAPHIFY_ROOT", Path.cwd())).resolve()
OUT = ROOT / "graphify-out"

# Generated or vendored trees, plus tooling docs that are not project
# knowledge. .claude/skills and AGENTS.md hold the GitNexus skill files: they
# are byte-identical across repositories and would otherwise form one large
# spurious "tooling" community that swamps the real architecture.
EXCLUDE = (
    "graphify-out",
    ".gitnexus",
    "docs/gitnexus",
    "docs/graphify",
    ".claude/skills",
    "node_modules",
    "/.git/",
    "/build/",
    "SmartWard.xcodeproj",
    "SourcePackages",
    ".github/workflows",
    "githooks",
)

# AGENTS.md is regenerated by `gitnexus analyze`; keep it out by exact name
# rather than a substring so a real "agents" doc would survive.
EXCLUDE_EXACT = ("AGENTS.md",)


def keep(p: str) -> bool:
    try:
        rel = str(Path(p).resolve().relative_to(ROOT)).replace("\\", "/")
    except ValueError:
        return False
    if rel in EXCLUDE_EXACT:
        return False
    return not any(part in rel for part in EXCLUDE)


def main() -> int:
    from graphify.analyze import god_nodes, surprising_connections, suggest_questions
    from graphify.build import build_from_json
    from graphify.cluster import cluster, score_all
    from graphify.detect import detect
    from graphify.export import to_json
    from graphify.extract import collect_files, extract
    from graphify.report import generate

    OUT.mkdir(exist_ok=True)

    # ---- Detect (with generated/infra dirs filtered out) ----
    result = detect(ROOT)
    result["files"] = {
        cat: [f for f in lst if keep(f)] for cat, lst in result.get("files", {}).items()
    }
    result["total_files"] = sum(len(v) for v in result["files"].values())
    print(f"Detected {result['total_files']} files")
    for cat, files in sorted(result["files"].items()):
        if files:
            print(f"  {cat}: {len(files)}")

    # ---- Part A: AST extraction for code (free, deterministic) ----
    code_files = []
    for f in result["files"].get("code", []):
        p = Path(f)
        code_files.extend(collect_files(p) if p.is_dir() else [p])
    if code_files:
        ast = extract(code_files, cache_root=ROOT)
        print(f"AST: {len(ast['nodes'])} nodes, {len(ast['edges'])} edges")
    else:
        ast = {"nodes": [], "edges": [], "input_tokens": 0, "output_tokens": 0}
        print("No code files - skipping AST extraction")

    # ---- Part B: semantic extraction for docs ----
    # Three paths, in priority order:
    #   1. A pre-built semantic cache. The tracked copy in
    #      docs/graphify/semantic-extraction.json is checked first so that CI
    #      and any fresh clone reproduce the same graph with no key at all.
    #      The copy in graphify-out/ is the local working file that the
    #      agent-assisted /graphify flow writes. This is what puts the design
    #      vocabulary in docs/PLAN.md into the graph, which AST cannot see.
    #   2. Gemini, when GEMINI_API_KEY is set. Use this to refresh the cache
    #      after the prose changes, then commit the new cache.
    #   3. Neither -> code-only graph, which is still useful and free.
    sem = {"nodes": [], "edges": [], "hyperedges": [], "input_tokens": 0, "output_tokens": 0}
    doc_files = [f for cat in ("document", "paper") for f in result["files"].get(cat, [])]
    candidates = (ROOT / "docs/graphify/semantic-extraction.json", OUT / ".graphify_semantic.json")
    prebuilt = next((p for p in candidates if p.exists()), None)
    if prebuilt:
        sem = json.loads(prebuilt.read_text(encoding="utf-8"))

        def relativize(obj):
            """Strip the absolute checkout prefix from source_file.

            The agent-assisted /graphify flow records absolute paths, which
            would bake the author's home directory into the committed graph and
            make the output differ per machine. Normalise to repo-relative.
            """
            changed = 0
            for item in obj:
                sf = item.get("source_file")
                if not isinstance(sf, str):
                    continue
                try:
                    rel = str(Path(sf).resolve().relative_to(ROOT)).replace("\\", "/")
                except ValueError:
                    continue
                if rel != sf:
                    item["source_file"] = rel
                    changed += 1
            return changed

        fixed = (
            relativize(sem.get("nodes", []))
            + relativize(sem.get("edges", []))
            + relativize(sem.get("hyperedges", []))
        )
        print(
            f"Semantic (pre-built): {len(sem.get('nodes', []))} nodes, "
            f"{len(sem.get('edges', []))} edges from {prebuilt.name}"
        )
        if fixed:
            print(f"  relativized {fixed} absolute source_file path(s)")
        # A cache older than the prose it describes silently drops new design
        # vocabulary, so say so rather than letting the graph look complete.
        newer = [f for f in doc_files if Path(f).exists() and Path(f).stat().st_mtime > prebuilt.stat().st_mtime]
        if newer:
            print(
                f"NOTE: {len(newer)} doc file(s) newer than the semantic cache, e.g. "
                f"{Path(sorted(newer)[0]).name}. Re-run the /graphify flow (or set "
                "GEMINI_API_KEY) and commit docs/graphify/semantic-extraction.json."
            )
    elif doc_files and os.environ.get("GEMINI_API_KEY"):
        from graphify.llm import extract_corpus_parallel

        sem = extract_corpus_parallel(doc_files, backend="gemini")
        print(f"Semantic (Gemini): {len(sem.get('nodes', []))} nodes from {len(doc_files)} docs")
    elif doc_files:
        print(
            f"NOTE: {len(doc_files)} doc files found but no semantic source "
            "(GEMINI_API_KEY unset, no .graphify_semantic.json) - graph is code-only"
        )

    # ---- Part C: merge AST + semantic ----
    seen = {n["id"] for n in ast["nodes"]}
    nodes = list(ast["nodes"])
    for n in sem.get("nodes", []):
        if n["id"] not in seen:
            nodes.append(n)
            seen.add(n["id"])
    merged = {
        "nodes": nodes,
        "edges": ast["edges"] + sem.get("edges", []),
        "hyperedges": sem.get("hyperedges", []),
        "input_tokens": sem.get("input_tokens", 0),
        "output_tokens": sem.get("output_tokens", 0),
    }

    # ---- Build, cluster, analyze, report ----
    G = build_from_json(merged, root=str(ROOT), directed=False)
    if G.number_of_nodes() == 0:
        print("ERROR: Graph is empty - extraction produced no nodes.")
        return 1

    communities = cluster(G)
    cohesion = score_all(G, communities)
    gods = god_nodes(G)
    surprises = surprising_connections(G, communities)

    # Deterministic labels: name each community after its highest-degree member.
    labels = {}
    for cid, members in communities.items():
        top = max(members, key=lambda n: G.degree(n))
        lbl = G.nodes[top].get("label") if isinstance(G.nodes[top], dict) else None
        labels[cid] = (str(lbl) if lbl else str(top))[:40]

    questions = suggest_questions(G, communities, labels)
    tokens = {
        "input": merged.get("input_tokens", 0),
        "output": merged.get("output_tokens", 0),
    }

    wrote = to_json(G, communities, str(OUT / "graph.json"), community_labels=labels)
    if not wrote:
        print("WARN: graph.json write refused (shrink guard #479) - keeping previous graph.json")
    else:
        # Drop the commit stamp so the graph is a pure function of the source
        # tree. Two problems with keeping it: the pre-commit hook builds before
        # the commit exists, so the recorded SHA could only ever be the parent,
        # and every commit would rewrite the field and leave the artifact dirty
        # forever. Git already records which commit each artifact landed in.
        gp = OUT / "graph.json"
        payload = json.loads(gp.read_text(encoding="utf-8"))
        if payload.pop("built_at_commit", None) is not None:
            gp.write_text(json.dumps(payload, ensure_ascii=False, indent=1), encoding="utf-8")
            print("Stripped built_at_commit so the artifact depends only on the source tree")

    report = generate(
        G,
        communities,
        cohesion,
        labels,
        gods,
        surprises,
        result,
        tokens,
        str(ROOT),
        suggested_questions=questions,
    )
    (OUT / "GRAPH_REPORT.md").write_text(report, encoding="utf-8")
    # The report header stamps the local date, so a local run and a CI run can
    # disagree by a day depending on the timezone and leave a date-only diff
    # that has nothing to do with the code. CI is UTC; pin the header to UTC so
    # both sides produce the same report for the same tree.
    rp = OUT / "GRAPH_REPORT.md"
    text = rp.read_text(encoding="utf-8")
    utc_today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    patched = re.sub(
        r"^(#\s*Graph Report\b.*?)\(\d{4}-\d{2}-\d{2}\)", rf"\g<1>({utc_today})", text, count=1
    )
    if patched != text:
        rp.write_text(patched, encoding="utf-8")
    (OUT / ".graphify_labels.json").write_text(
        json.dumps({str(k): v for k, v in labels.items()}, ensure_ascii=False), encoding="utf-8"
    )

    print(
        f"Graph: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges, "
        f"{len(communities)} communities"
    )
    print(f"Tokens: {tokens['input']:,} in / {tokens['output']:,} out")
    return 0


if __name__ == "__main__":
    sys.exit(main())
